modified debug watch-agent

diff --git a/debug/watch-agent b/debug/watch-agent
--- a/debug/watch-agent
+++ b/debug/watch-agent
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-#TIMEOUT_S="10"
-#LATER=$((`date +%s` + $TIMEOUT_S))
+TIMEOUT_S="600"
+LATER=$((`date +%s` + $TIMEOUT_S))
 HOSTNAME=`hostname`
 
 while [ true ]; do
@@ -9,20 +9,20 @@ while [ true ]; do
     # returns 255 if ssh/vcmd session fails
 
     # Check if servald is running
-    if [ $(servald status | grep stopped | wc -l) -eq 1 ]; then
-        echo "ERROR: Serval crashed on $HOSTNAME" >&2
-        exit 2
-    fi
+    #if [ $(servald status | grep stopped | wc -l) -eq 1 ]; then
+    #    echo "ERROR: Serval crashed on $HOSTNAME" >&2
+    #    exit 2
+    #fi
 
     # Check if test timed out
-    #if [ "$LATER" -lt `date +%s` ]; then
-        # echo "ERROR: Timeout on $HOSTNAME" >&2
-        # exit 3
+    if [ "$LATER" -lt `date +%s` ]; then
+         echo "Finished: Timeout on $HOSTNAME" >&2
+         exit 0
         
         # exit 0 is fine here, for debug purposes
     #    echo "Serval finished on $HOSTNAME" >&2
     #    exit 0
-    #fi
+    fi
 
     sleep 15
 done
