Detailed Output for debugging

diff --git a/debug/watch-agent b/debug/watch-agent
--- a/debug/watch-agent
+++ b/debug/watch-agent
@@ -9,16 +9,17 @@ while [ true ]; do
 
     # Check if servald is running
     if [ `(ps aux 2> /dev/null || ps w) | grep "servald start" | grep -v grep | wc -l` -lt 1 ]; then
-        echo "Serval crashed on $HOSTNAME" >&2
+        echo "ERROR: Serval crashed on $HOSTNAME" >&2
         exit 2
     fi
 
     # Check if test timed out
     if [ "$LATER" -lt `date +%s` ]; then
-        # echo "Timeout on $HOSTNAME" >&2
+        # echo "ERROR: Timeout on $HOSTNAME" >&2
         # exit 3
         
         # exit 0 is fine here, for debug purposes
+        echo "Serval finished on $HOSTNAME" >&2
         exit 0
     fi
 
