remove miniworld traceback log before new watcher start

diff --git a/auto-scenario b/auto-scenario
--- a/auto-scenario
+++ b/auto-scenario
@@ -3,15 +3,17 @@
 MINIWORLD_TRACEBACK_PATH=/root/miniworld/MiniWorld/miniworld_traceback.log
 
 rpc_runloop_exception_handler () {
-    echo -e "\e[37m\e[44m# Exception occured on RPC runloop. See '$MINIWORLD_TRACEBACK_PATH' for more information:\e[0m"
+    echo -e "\e[37m\e[44m# Either an exception occured on the RPC runloop or the RPC server is not started at all!. See '$MINIWORLD_TRACEBACK_PATH' for runloop errors:\e[0m"
     cp $MINIWORLD_TRACEBACK_PATH $LOGFOLDER/miniworld_traceback.log
     cat $MINIWORLD_TRACEBACK_PATH
-    echo -e "\e[37m\e[44m# Fully aborting auto-scenario!\e[0m"
-    exit 1
+    #echo -e "\e[37m\e[44m# Fully aborting auto-scenario!\e[0m"
+    echo -e "\e[37m\e[44m# --- ignoring for now!\e[0m"
+    #exit 1
 }
 
 start_rpc_watcher() {
     echo -e "\e[37m\e[44m# Starting RPC watcher...\e[0m"
+    rm $MINIWORLD_TRACEBACK_PATH
 	(cd /root/miniworld/MiniWorld && python miniworld/rpc/RPCCheckErrors.py -pg $MAIN_PROCESS_PID -t $MINIWORLD_TRACEBACK_PATH -s 10 MiniWorld_Scenarios/serval_paper/$1 > /dev/null) &
     WATCHER_PID=$!
 }
