added example line which is useful when debugging "shrinked" scenarios (eg. 30 booted nodes in a 100 nodes scenario)

diff --git a/scenario b/scenario
--- a/scenario
+++ b/scenario
@@ -123,6 +123,8 @@ elif [ "$TYPE" == "miniworld" ]; then
         for PID in $PIDS; do
             wait $PID || let "FAIL=$?"
             printf .
+            # Activate line to investigate bugs caused by "shrinked" scenarios
+            # if [ "$FAIL" != "0" ]; then echo -e "\e[1;31mPID $PID failed with $FAIL, aborting scenario.\e[0m"; echo "Time to investigate!"; sleep 300; exit 10; fi
             if [ "$FAIL" != "0" ]; then echo -e "\e[1;31mPID $PID failed with $FAIL, aborting scenario.\e[0m"; exit 1; fi
         done
         echo
