prepare, watch and initiate are now parameterizable

diff --git a/mass-inject-file/watch-agent b/mass-inject-file/watch-agent
--- a/mass-inject-file/watch-agent
+++ b/mass-inject-file/watch-agent
@@ -5,6 +5,8 @@ LATER=$((`date +%s` + $TIMEOUT_S))
 HOSTNAME=`hostname`
 
 while [ true ]; do
+    # exit 1 if script itself fails
+    
     # Check if servald is running
     if [ $(ps aux | grep "servald start" | grep -v grep | wc -l) -lt 1 ]; then 
         echo "Serval crashed on $HOSTNAME" >&2
