NOT FINISHED! Watch agent finished. Still a bug with forking the seperate initiates to the background. Is currently disabled, so everything will be executed sequentielly.

diff --git a/combined/watch-agent b/combined/watch-agent
--- a/combined/watch-agent
+++ b/combined/watch-agent
@@ -1,32 +1,37 @@
 #!/bin/sh
 
+TIMEOUT_S="500"
+LATER=$((`date +%s` + $TIMEOUT_S))
+HOSTNAME=`hostname`
+
 TOTAL_NODES="$1"
 TOTAL_ACTIVE_NODES="$2"
+TIME_VAL="$3"
 
-TIME_DM="t"
-TIME_VAL_DM="$3"
+SCENARIO_TIMEOUT="$TIME_VAL"
+SCENARIO_LATER=$((`date +%s` + $SCENARIO_TIMEOUT))
 
-TIME_DDF="t"
-TIME_VAL_DDF="$3"
+while [ true ]; do
+    # returns 1 if script itself fails
+    # returns 255 if ssh/vcmd session fails
 
-COUNT_OR_TIME_DF="$4"
-COUNT_OR_TIME_VAL_DF="$5"
+    # Check if servald is running
+    if [ `(ps aux 2> /dev/null || ps w) | grep "servald start" | grep -v grep | wc -l` -lt 1 ]; then
+        echo "ERROR: Serval crashed on $HOSTNAME" >&2
+        exit 2
+    fi
 
-NUM_MIF="$6"
+    # Check if test timed out
+    if [ "$LATER" -lt `date +%s` ]; then
+        echo "ERROR: Timeout on $HOSTNAME" >&2
+        exit 3
+    fi
 
-NUM_MSGS_MIM="$7"
+    # Check if condition is reached
+    if [ "$SCENARIO_LATER" -lt `date +%s` ]; then
+    	echo "Watch-agents successfully finished after $TIME_VAL seconds on $HOSTNAME"
+    	exit 0
+    fi
 
-echo "Initiating delayed messages..."
-/bin/sh watch-agent-delayed-messages $TOTAL_NODES $TOTAL_ACTIVE_NODES $TIME_DM $TIME_DM_VAL
-
-echo "Initiating delayed direct files..."
-/bin/sh watch-agent-delayed-direct-files $TOTAL_NODES $TOTAL_ACTIVE_NODES $TIME_DDF $TIME_VAL_DDF
-
-echo "Initiating delayed files..."
-/bin/sh watch-agent-delayed-files $TOTAL_NODES $TOTAL_ACTIVE_NODES $COUNT_OR_TIME_DF $COUNT_OR_TIME_VAL_DF
-
-echo "Initiating mass inject files..."
-/bin/sh watch-agent-mass-inject-files $TOTAL_NODES $TOTAL_ACTIVE_NODES $NUM_MIF
-
-echo "Initiating mass inject messages..."
-/bin/sh watch-agent-mass-inject-messages $TOTAL_NODES $TOTAL_ACTIVE_NODES $NUM_MSGS_MIM
+    sleep 1
+done
